package com.wojtek.Metaprogramming.CompileTime

import groovy.transform.CompileStatic
import groovy.transform.TypeCheckingMode

@CompileStatic
class Class {

    // Similar to TypeChecked, but it skips MOP, closer to Java generated bytecode

    String foo(){
        "foo"
    }

    String bar(){
        "bar"
    }
    @CompileStatic(TypeCheckingMode.SKIP)
    void noReturn(){

    }
}
